---
  - name: install dependencies
    yum: name={{item}} state=present
    with_items:
      - gcc
      - libyaml-devel
      - glibc-headers
      - autoconf
      - gcc-c++
      - glibc-devel
      - automake
      - libtool
      - bison
      - nodejs

  - name: copy install script
    copy: src=install_ruby.sh dest=/tmp/install_ruby.sh mode=0755

  - name: run install script
    shell: sudo -i /tmp/install_ruby.sh

